x-google-allow: all
swagger: "2.0"
info:
  title: Users and documents API
  description: This API is used in document-validation APP
  version: 1.1.0
host: document-validator.appspot.com
x-google-endpoints:
  - name: document-validator.appspot.com
    allowCors: True
basePath: /v1
schemes:
  - https
paths:
  /status:
    get:
      summary: Return the status
      operationId: status
      produces:
        - string
      responses:
        200:
          description: OK
        500:
          description: Error in Status
      security:
        - api_key: []
  /users:
    get:
      summary: Returns a list of users.
      operationId: getUsers
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Error getting users
      security:
        - api_key: []
    post:
      summary: Creates a new user.
      operationId: postUser
      parameters:
        - in: body
          name: user
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: OK
        500:
          description: Error creating user
      security:
        - api_key: []
  /users/{id}:
    get:
      summary: Return a user based on ID.
      operationId: getUserById
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Error getting user
      security:
        - api_key: []
    put:
      summary: Edit a user
      operationId: editUser
      parameters:
        - in: body
          name: user
          schema:
            $ref: "#/definitions/User"
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: User edited successfully
        500:
          description: Error editing user
      security:
        - api_key: []
    delete:
      summary: delete a user
      operationId: deleteUser
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: User deleted successfully
        500:
          description: Error deleting user
      security:
        - api_key: []
  /users/username/{username}:
    get:
      summary: Return a user based on username.
      operationId: getUserByUsername
      parameters:
        - in: path
          name: username
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Error getting user
      security:
        - api_key: []
  /documents:
    post:
      summary: Creates a new document.
      operationId: postDocument
      parameters:
        - in: body
          name: document
          schema:
            $ref: "#/definitions/Document"
      responses:
        200:
          description: OK
        500:
          description: Error creating document
      security:
        - api_key: []
  /documents/{id}:
    delete:
      summary: delete a document
      operationId: deleteDocument
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: Document deleted successfully
        500:
          description: Error deleting document
      security:
        - api_key: []
    get:
      summary: Return the list of documents linked to the userId passed.
      operationId: getDocumentsByUserId
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Error getting user
      security:
        - api_key: []

  /validations:
    post:
      summary: Creates a new validation.
      operationId: postValidation
      parameters:
        - in: body
          name: validation
          schema:
            $ref: "#/definitions/Validation"
      responses:
        200:
          description: OK
        500:
          description: Error creating validation
      security:
        - api_key: []
  /validations/{id}:
    get:
      summary: Return the list of validation linked to the fileId passed.
      operationId: getValidationByFileId
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Error getting validation
      security:
        - api_key: []
    delete:
      summary: delete a validation
      operationId: deleteValidation
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: Validaiton deleted successfully
        500:
          description: Error deleting validation
      security:
        - api_key: []

definitions:
  #Phone:
  #  type: "object"
  #  properties:
  #    phoneId:
  #      type: "integer"
  #      format: "int64"
  #    userId:
  #      type: "integer"
  #      format: "int64"
  #    phonNumber:
  #      type: "string"
  User:
    type: "object"
    properties:
      username:
        type: "string"
      fullName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phones:
        type: "array"
        items:
          type: "string"
  Document:
    type: "object"
    properties:
      userId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      url:
        type: "string"
  Validation:
    type: "object"
    properties:
      fileId:
        type: "integer"
        format: "int64"
      base64:
        type: "string"
      motivation:
        type: "string"

# [START securityDef]
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
# [END securityDef]
